version: "3"
services:
  backend:
    restart: always
    build:
        context: ./backend
    ports:
        - "3001:3001"
    env_file:
        - ./backend/.env
    volumes:
        - ./backend/src:/usr/app/src
        - ./backend/tests:/usr/app/tests
  frontend:
    restart: always
    build:
        context: ./frontend
    ports: 
        - "3000:3000"
    volumes:
        - ./frontend/src:/usr/app/src
    stdin_open: true
    depends_on:
    - backend